version: '3.4'
services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    environment: 
      - NETWORK_ID=${NETWORK_ID}
      - DATA_FOLDER=${DATA_FOLDER}
      - PORT=${PORT}
      - ADDRESS_COUNT=${ADDRESS_COUNT}
      - MNEMONIC=${MNEMONIC}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ${DATA_FOLDER}:/ganache_data
    command: "ganache-cli --deterministic --db=/ganache_data --mnemonic '${MNEMONIC}' --networkId ${NETWORK_ID} --hostname 0.0.0.0 --port ${PORT} -a ${ADDRESS_COUNT} --defaultBalanceEther 1000"