name: Test Changed or New Files under test/

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Build Project
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      INFURA_KEY: my-infura-key-here
      GAS_PRICE_GWEI_KEY: 20
      GAS_WEI_KEY: 2500000
      MNEMONIC_KEY: my-mnemonic-value-here
      ADDRESS_COUNT_KEY: 5
      DEFAULT_ADDRESS_INDEX_KEY: 0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.15.x'
      - id: files
        name: Get List of Changed Files
        uses: jitterbit/get-changed-files@v1
      - name: Main
        env:
          CHANGED_FILES: "${{ steps.files.outputs.added_modified  }}"
        run: |
          CHANGED_TEST_FILES=`echo "$CHANGED_FILES" | tr " " '\n' | grep 'test/' | tr '\n' " "`
          if [ "$CHANGED_TEST_FILES" ]; then yarn && yarn compile && yarn typechain && yarn test $CHANGED_TEST_FILES; fi
