name: Compile & Run Smart Contract Unit Tests

on: [pull_request]

jobs:
  test:
    name: Build Project
    runs-on: ubuntu-latest
    env:
      ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
      INFURA_KEY: ${{ secrets.INFURA_KEY }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      GAS_PRICE_GWEI_KEY: 20
      GAS_WEI_KEY: 2500000
      MNEMONIC_KEY: ${{ secrets.MNEMONIC_KEY }}
      ADDRESS_COUNT_KEY: 10
      DEFAULT_ADDRESS_INDEX_KEY: 0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.x'
      - name: Install dependencies
        run: |
          yarn
      - name: Compiling Smart Contracts
        run: |
          yarn compile
      - name: Executing Tests
        run: |
          yarn hardhat test
